### ISSUE TITLE
Heroku Free Plan Shutdown (hosting solution help)

### ISSUE THREAD

**Issue by Bellisario** [Bellisario/node-snapdrop#15]
On November 28, node-snapdrop public server will stop working because of [Heroku Free Plan Shutdown](https://blog.heroku.com/next-chapter).
Since I cannot spend money to keep running this server my own, it will be shutdown because I'll not have "free dynos" anymore.

I'm asking all the Snapdrop and node-snapdrop community to help this open-source project keep running by proposing new free hosting solutions that are compatible with technologies used here.

Remember also node-snapdrop have to keep WebSocket connections for clients discover, so for example Serverless Functions (Vercel, etc...) won't work properly.

---

> Starting November 28, 2022, we plan to stop offering free product plans and plan to start shutting down free dynos and data services.
> _- Heroku Next Chapter_

**Comment by iaeiou** [comment]
Damn, sorry to hear that!
I don't know the requirements enough, but a starting point could be this article I stumbled upon today on dev.to: https://dev.to/jainilprajapati/7-fantastic-heroku-alternatives-4jf8

**Comment by r-40021** [comment]
I found Render as a solution for deploying Node.js apps.
You can deploy them in the same way as Heroku.
https://render.com/docs/deploy-node-express-app

**Comment by Bellisario** [comment]
Thanks very much @iaeiou and @r-40021, I opted for Render!

> The new server URL it's here:
> https://node-snapdrop.onrender.com

---

Anyway, I'll keep the Heroku server active as long as possible, but I think I'll delete app re-build on repo push since I'm let it die...
