### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by ObT1337** [Bellisario/node-snapdrop#36]
The first boot worked just fine.

When I restart the program I always geht the Error message:
"ERR_TOO_MANY_REDIRECTS", whenever I try to access the webpage.

I run it on a raspberry pi 3B+

**Comment by Bellisario** [comment]
@ObT1337 so it works now?

**Comment by ObT1337** [comment]
Yes it does. One has always to be in the directory `node-snapdrop` and then execute `node index.js`.

Thanks again!
